export const catalogo = [
    { 'src': '/imgs/inicio/catalogo/sofa_helena.png', 'name': 'Sofá Helena' },
    { 'src': '/imgs/inicio/catalogo/sofa_barro.png', 'name': 'Sofá Barró' },
    { 'src': '/imgs/inicio/catalogo/sofa_media_luna.png', 'name': 'Sofá Media Luna' },
    { 'src': '/imgs/inicio/catalogo/sofa_rosset.png', 'name': 'Sofá Rosset' },
    { 'src': '/imgs/inicio/catalogo/sofa_modular.png', 'name': 'Sofá Modular' },
    { 'src': '/imgs/inicio/catalogo/sofa_anati.png', 'name': 'Sofá Anati' },
    { 'src': '/imgs/inicio/catalogo/silla_raun.png', 'name': 'Silla Raun' },
    { 'src': '/imgs/inicio/catalogo/silla_melati.png', 'name': 'Silla Melati' },
    { 'src': '/imgs/inicio/catalogo/silla_roy.png', 'name': 'Silla Roy' },
    { 'src': '/imgs/inicio/catalogo/sitial_marath.png', 'name': 'Sitial Marath' },
    { 'src': '/imgs/inicio/catalogo/sitial_barro.png', 'name': 'Sitial Barró' },
    { 'src': '/imgs/inicio/catalogo/sitial_trama.png', 'name': 'Sitial Trama' },
    { 'src': '/imgs/inicio/catalogo/sitial_polo.png', 'name': 'Sitial Polo' },
    { 'src': '/imgs/inicio/catalogo/reposera_madera.png', 'name': 'Reposera Madera' },
    { 'src': '/imgs/inicio/catalogo/sitial_julio_iglesias.png', 'name': 'Sitial Julio Iglesias' },
    { 'src': '/imgs/inicio/catalogo/silla_crossback.png', 'name': 'Sillas Crossback' },
    { 'src': '/imgs/inicio/catalogo/silla_bambu.png', 'name': 'Silla Bambú' },
    { 'src': '/imgs/inicio/catalogo/piso_bar_bali.png', 'name': 'Piso Bar Bali' },
    { 'src': '/imgs/inicio/catalogo/piso_bar_negro.png', 'name': 'Piso Bar Negro' },
    { 'src': '/imgs/inicio/catalogo/piso_bar_tolix_blanco.png', 'name': 'Piso Bar Tolix Blanco' },
    { 'src': '/imgs/inicio/catalogo/piso_bar_tolix_negro.png', 'name': 'Piso Bar Tolix Negro' },
    { 'src': '/imgs/inicio/catalogo/pouf_alana.png', 'name': 'Pouf Alana' },
    { 'src': '/imgs/inicio/catalogo/pouf_miller.png', 'name': 'Pouf Miller' },
    { 'src': '/imgs/inicio/catalogo/pouf_redondo.png', 'name': 'Pouf Redondo' },
    { 'src': '/imgs/inicio/catalogo/pouf_boho.png', 'name': 'Pouf Boho' },
    { 'src': '/imgs/inicio/catalogo/pouf_fibra.png', 'name': 'Pouf Fibra' },
    { 'src': '/imgs/inicio/catalogo/pouf_kila.png', 'name': 'Pouf Kila' },
    { 'src': '/imgs/inicio/catalogo/pisp_tejido.png', 'name': 'Piso Tejido' },
    { 'src': '/imgs/inicio/catalogo/piso_yucatan.png', 'name': 'Piso Yucatán' },
    { 'src': '/imgs/inicio/catalogo/piso_vallarta.png', 'name': 'Piso Vallarta' },
    { 'src': '/imgs/inicio/catalogo/banqueta_tulum.png', 'name': 'Banqueta Tulum' },
    { 'src': '/imgs/inicio/catalogo/banqueta_madera.png', 'name': 'Banqueta Madera' },
    { 'src': '/imgs/inicio/catalogo/mesa_ratan.png', 'name': 'Mesa Ratán' },
    { 'src': '/imgs/inicio/catalogo/mesa_monteverde.png', 'name': 'Mesa Monteverde' },
    { 'src': '/imgs/inicio/catalogo/mesa_tronco.png', 'name': 'Mesa Tronco' },
    { 'src': '/imgs/inicio/catalogo/mesa_niagara.png', 'name': 'Mesa Niagara' },
    { 'src': '/imgs/inicio/catalogo/mesa_toulousse.png', 'name': 'Mesa Toulousse' },
    { 'src': '/imgs/inicio/catalogo/mesa_roble.png', 'name': 'Mesa Roble' },
    { 'src': '/imgs/inicio/catalogo/mesas_grape.png', 'name': 'Set Mesas Grape' },
    { 'src': '/imgs/inicio/catalogo/mesa_lateral_melati.png', 'name': 'Mesa Lateral Melati' },
    { 'src': '/imgs/inicio/catalogo/mesa_bar_bali.png', 'name': 'Mesa Bar Bali' },
    { 'src': '/imgs/inicio/catalogo/mesa_bar_alamo.png', 'name': 'Mesa Bar Álamo' },
    { 'src': '/imgs/inicio/catalogo/mesa_bar_ele.png', 'name': 'Mesa Bar Ele' },
    { 'src': '/imgs/inicio/catalogo/meson_rustico.png', 'name': 'Mesón Rústico' },
    { 'src': '/imgs/inicio/catalogo/mesa_plegable_60x180.png', 'name': 'Mesa Plegable' },
    { 'src': '/imgs/inicio/catalogo/arrimo_ceremonia.png', 'name': 'Arrimo Ceremonia' },
    { 'src': '/imgs/inicio/catalogo/alfombra_yute.png', 'name': 'Alfombra Yute Natural (200x300)' },
    { 'src': '/imgs/inicio/catalogo/alfombra_yute.png', 'name': 'Alfombra Yute Natural (160x230)' },
    { 'src': '/imgs/inicio/catalogo/alfombra_beige.png', 'name': 'Alfombra Beigi (160x230)' },
    { 'src': '/imgs/inicio/catalogo/alfombra_blanca.png', 'name': 'Alfombra Blanca (160x230)' },
    { 'src': '/imgs/inicio/catalogo/alfombra_yute_redonda.png', 'name': 'Alfombra Yute Redonda Beige (120)' },
    { 'src': '/imgs/inicio/catalogo/pasto_sintetico.png', 'name': 'Pasto Sintético (400x200)' },
    { 'src': '/imgs/inicio/catalogo/pasto_sintetico.png', 'name': 'Pasto Sintético (400x400)' },
    { 'src': '/imgs/inicio/catalogo/barra_bar_reveri.png', 'name': 'Barra Bar Reveri' },
    { 'src': '/imgs/inicio/catalogo/quitasol.png', 'name': 'Quitasol Blanco Madera' },
    { 'src': '/imgs/inicio/catalogo/plantas.png', 'name': 'Plantas Deco' },
    { 'src': '/imgs/inicio/catalogo/manta_cojines.png', 'name': 'Set Deco Manta y 2 Cojines' },
    { 'src': '/imgs/inicio/catalogo/canastos_1.png', 'name': 'Set 3 Canastos 1' },
    { 'src': '/imgs/inicio/catalogo/canastos_2.png', 'name': 'Set 3 Canatastos 2' },
    { 'src': '/imgs/inicio/catalogo/canastos_3.png', 'name': 'Set 3 Canatastos 3' },
    { 'src': '/imgs/inicio/catalogo/lampara_chilote.png', 'name': 'Lámpara Chilote' },
    { 'src': '/imgs/inicio/catalogo/lampara_bambu.png', 'name': 'Lámpara Bambú' },
    { 'src': '/imgs/inicio/catalogo/lampara_mariposa.png', 'name': 'Lámpara Fibra Mariposa' },
    { 'src': '/imgs/inicio/catalogo/candelabro_pie.png', 'name': 'Candelabro Pie' },
    { 'src': '/imgs/inicio/catalogo/3_candelabros.png', 'name': 'Set 3 Candelabros' },
    { 'src': '/imgs/inicio/catalogo/baul_rustico.png', 'name': 'Baúl Rústico' },
    { 'src': '/imgs/inicio/catalogo/estufa_gas.png', 'name': 'Estufa Gas (Con Gas)' },
    { 'src': '/imgs/inicio/catalogo/visicooler.png', 'name': 'Visicooler 360L' },
    { 'src': '/imgs/inicio/catalogo/atril.png', 'name': 'Atril' },
    { 'src': '/imgs/inicio/catalogo/arco.png', 'name': 'Arco' },
    { 'src': '/imgs/inicio/catalogo/respaldo.png', 'name': 'Respaldo Barra Madera' },
    { 'src': '/imgs/inicio/catalogo/espejo_piso.png', 'name': 'Espejo Piso' },
    { 'src': '/imgs/inicio/catalogo/arco_cuadrado.png', 'name': 'Arco Ceremonia Cuadrado' },
    { 'src': '/imgs/inicio/catalogo/arco_triangular.png', 'name': 'Arco Ceremonio Triangular' },
    { 'src': '/imgs/inicio/catalogo/biombo_arpi.png', 'name': 'Biombo Arpi' },
]