export const catalogo = [
    { 'src': '/imgs/inicio/catalogo/img1.png', 'name': 'Sofá Modular' },
    { 'src': '/imgs/inicio/catalogo/img2.png', 'name': 'Sofá Anati' },
    { 'src': '/imgs/inicio/catalogo/img3.jpg', 'name': 'Silla Raun' },
    // { 'src': '/imgs/inicio/catalogo/img4.jpg', 'name': 'Silla Melati' },
    // { 'src': '/imgs/inicio/catalogo/img5.jpg', 'name': 'Silla Roy' },
    // { 'src': '/imgs/inicio/catalogo/img6.jpg', 'name': 'Sitial Marath' },
    // { 'src': '/imgs/inicio/catalogo/img7.jpg', 'name': 'Sitial Barró' },
    // { 'src': '/imgs/inicio/catalogo/img8.jpg', 'name': 'Sitial Trama' },
    // { 'src': '/imgs/inicio/catalogo/img9.jpg', 'name': 'Sitial Polo' },
    // { 'src': '/imgs/inicio/catalogo/img10.jpg', 'name': 'Reposera Madera' },
    // { 'src': '/imgs/inicio/catalogo/img11.jpg', 'name': 'Sitial Julio Iglesias' },
    // { 'src': '/imgs/inicio/catalogo/img12.jpg', 'name': 'Sillas Crossback' },
    // { 'src': '/imgs/inicio/catalogo/img13.jpg', 'name': 'Silla Bambú' },
    // { 'src': '/imgs/inicio/catalogo/img14.jpg', 'name': 'Piso Bar Bali' },
    // { 'src': '/imgs/inicio/catalogo/img15.jpg', 'name': 'Piso Bar Negro' },
    // { 'src': '/imgs/inicio/catalogo/img16.jpg', 'name': 'Piso Bar Tolix Blanco' },
    // { 'src': '/imgs/inicio/catalogo/img17.jpg', 'name': 'Piso Bar Tolix Negro' },
    // { 'src': '/imgs/inicio/catalogo/img18.jpg', 'name': 'Pouf Alana' },
    // { 'src': '/imgs/inicio/catalogo/img19.jpg', 'name': 'Pouf Miller' },
    // { 'src': '/imgs/inicio/catalogo/img20.jpg', 'name': 'Pouf Redondo' },
    // { 'src': '/imgs/inicio/catalogo/img21.jpg', 'name': 'Pouf Boho' },
    // { 'src': '/imgs/inicio/catalogo/img22.jpg', 'name': 'Pouf Fibra' },
    // { 'src': '/imgs/inicio/catalogo/img23.jpg', 'name': 'Pouf Kila' },
    // { 'src': '/imgs/inicio/catalogo/img24.jpg', 'name': 'Piso Tejido' },
    // { 'src': '/imgs/inicio/catalogo/img25.jpg', 'name': 'Piso Yucatán' },
    // { 'src': '/imgs/inicio/catalogo/img26.jpg', 'name': 'Piso Vallarta' },
    // { 'src': '/imgs/inicio/catalogo/img27.jpg', 'name': 'Banqueta Tulum' },
    // { 'src': '/imgs/inicio/catalogo/img28.jpg', 'name': 'Banqueta Madera' },
    // { 'src': '/imgs/inicio/catalogo/img29.jpg', 'name': 'Mesa Ratán' },
    // { 'src': '/imgs/inicio/catalogo/img30.jpg', 'name': 'Mesa Monteverde' },
    // { 'src': '/imgs/inicio/catalogo/img31.jpg', 'name': 'Mesa Tronco' },
    // { 'src': '/imgs/inicio/catalogo/img32.jpg', 'name': 'Mesa Niagara' },
    // { 'src': '/imgs/inicio/catalogo/img33.jpg', 'name': 'Mesa Toulousse' },
    // { 'src': '/imgs/inicio/catalogo/img34.jpg', 'name': 'Mesa Roble' },
    // { 'src': '/imgs/inicio/catalogo/img35.jpg', 'name': 'Set Mesas Grape' },
    // { 'src': '/imgs/inicio/catalogo/img36.jpg', 'name': 'Mesa Lateral Melati' },
    // { 'src': '/imgs/inicio/catalogo/img37.jpg', 'name': 'Mesa Bar Bali' },
    // { 'src': '/imgs/inicio/catalogo/img38.jpg', 'name': 'Mesa Bar Álamo' },
    // { 'src': '/imgs/inicio/catalogo/img39.jpg', 'name': 'Mesa Bar Ele' },
    // { 'src': '/imgs/inicio/catalogo/img40.jpg', 'name': 'Mesón Rústico' },
    // { 'src': '/imgs/inicio/catalogo/img41.jpg', 'name': 'Mesa Plegable' },
    // { 'src': '/imgs/inicio/catalogo/img42.jpg', 'name': 'Arrimo Ceremonia' },
    // { 'src': '/imgs/inicio/catalogo/img43.jpg', 'name': 'Alfombra Yute Natural (200x300)' },
    // { 'src': '/imgs/inicio/catalogo/img43.jpg', 'name': 'Alfombra Yute Natural (160x230)' },
    // { 'src': '/imgs/inicio/catalogo/img44.jpg', 'name': 'Alfombra Beigi (160x230)' },
    // { 'src': '/imgs/inicio/catalogo/img45.jpg', 'name': 'Alfombra Blanca (160x230)' },
    // { 'src': '/imgs/inicio/catalogo/img46.jpg', 'name': 'Alfombra Yute Redonda Beige (120)' },
    // { 'src': '/imgs/inicio/catalogo/img47.jpg', 'name': 'Pasto Sintético (400x200)' },
    // { 'src': '/imgs/inicio/catalogo/img47.jpg', 'name': 'Pasto Sintético (400x400)' },
    // { 'src': '/imgs/inicio/catalogo/img48.jpg', 'name': 'Barra Bar Reveri' },
    // { 'src': '/imgs/inicio/catalogo/img49.jpg', 'name': 'Quitasol Blanco Madera' },
    // { 'src': '/imgs/inicio/catalogo/img50.jpg', 'name': 'Plantas Deco' },
    // { 'src': '/imgs/inicio/catalogo/img51.jpg', 'name': 'Set Deco Manta y 2 Cojines' },
    // { 'src': '/imgs/inicio/catalogo/img52.jpg', 'name': 'Set 3 Canastos 1' },
    // { 'src': '/imgs/inicio/catalogo/img53.jpg', 'name': 'Set 3 Canatastos 2' },
    // { 'src': '/imgs/inicio/catalogo/img54.jpg', 'name': 'Set 3 Canatastos 3' },
    // { 'src': '/imgs/inicio/catalogo/img55.jpg', 'name': 'Lámpara Chilote' },
    // { 'src': '/imgs/inicio/catalogo/img56.jpg', 'name': 'Lámpara Bambú' },
    // { 'src': '/imgs/inicio/catalogo/img57.jpg', 'name': 'Lámpara Fibra Mariposa' },
    // { 'src': '/imgs/inicio/catalogo/img58.jpg', 'name': 'Candelabro Pie' },
    // { 'src': '/imgs/inicio/catalogo/img59.jpg', 'name': 'Set 3 Candelabros' },
    // { 'src': '/imgs/inicio/catalogo/img60.jpg', 'name': 'Baúl Rústico' },
    // { 'src': '/imgs/inicio/catalogo/img61.jpg', 'name': 'Estufa Gas (Con Gas)' },
    // { 'src': '/imgs/inicio/catalogo/img62.jpg', 'name': 'Visicooler 360L' },
    // { 'src': '/imgs/inicio/catalogo/img63.jpg', 'name': 'Atril' },
    // { 'src': '/imgs/inicio/catalogo/img64.jpg', 'name': 'Arco' },
    // { 'src': '/imgs/inicio/catalogo/img65.jpg', 'name': 'Respaldo Barra Madera' },
    // { 'src': '/imgs/inicio/catalogo/img66.jpg', 'name': 'Espejo Piso' },
    // { 'src': '/imgs/inicio/catalogo/img67.jpg', 'name': 'Arco Ceremonia Cuadrado' },
    // { 'src': '/imgs/inicio/catalogo/img68.jpg', 'name': 'Arco Ceremonio Triangular' },
    // { 'src': '/imgs/inicio/catalogo/img69.jpg', 'name': 'Biombo Arpi' },
    // { 'src': '/imgs/inicio/catalogo/img70.jpg', 'name': 'Sofá Helena' },
    // { 'src': '/imgs/inicio/catalogo/img71.jpg', 'name': 'Sofá Barró' },
    // { 'src': '/imgs/inicio/catalogo/img72.jpg', 'name': 'Sofá Media Luna' },
    // { 'src': '/imgs/inicio/catalogo/img73.jpg', 'name': 'Sofá Rosset' },
]