import { gothic, bebas } from "./ui/fonts";
import "./globals.css";
import Navbar from "./ui/layout/Navbar";
import Footer from "./ui/layout/Footer";

export const metadata = {
  title: "Modulari",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={`${bebas.variable} ${gothic.variable}`}>
      <body className="mt-25 sm:text-lg">

        <Navbar />
        {children}
        <Footer />
        
      </body>
    </html>
  );
}
